### ISSUE TITLE
[MINOR] Это как?

### ISSUE THREAD

**Issue by apetrin** [sandello/bigdatashad-2015#10]
![Это как?](https://pp.vk.me/c627219/v627219774/291b3/oY2-PRpnSb4.jpg)

У нас ничего не сломалось в мапредьюсе? :-)

**Comment by ShAlex** [comment]
А что тебе не нравится? Что тебе кажется в твоем скриншоте похоже не поломку MR?

**Comment by apetrin** [comment]
Мне кажется, что невозможно начинать reduce до того, как посчитаны map на 100%. Я не прав?

**Comment by ShAlex** [comment]
Ты не прав. См. Hadoop: The Definitive Guide. Chapter2.

**Comment by apetrin** [comment]
Александр, спасибо!
Для людей без книжки со слоником об этом можно почитать вот здесь: http://stackoverflow.com/questions/10192459/reduce-jobs-only-when-all-mappers-finish
Смысл в том, что процент reduce это не процент готовности reduce операции, а составной индекс: с 0 до 33% shuffle, 34-66 sort, 67-100% собственно операцию reduce.

Таким образом это означает лишь то, что shuffle какой-то джобы начался до того, как добежали все мапы, никакого криминала. Начинать _собственно_ reduce до того, закончится map нельзя
