### ISSUE TITLE
[HW2][QUESTION] Считать ли посещение страницы "/" хитом? профилем?

### ISSUE THREAD

**Issue by apetrin** [sandello/bigdatashad-2015#11]
Вопрос по каждой из пяти метрик.
Вроде бы ``суммарное количество запросов определенного пользователя к веб-сайту (по часам),`` означает что да, но вместе с этим это не профиль

**Comment by sandello** [comment]
Это не профиль (поэтому в profile_hits не считаются), но это хит от пользователя (поэтому в user_hits) считается.

**Comment by apetrin** [comment]
Спасибо!
