### ISSUE TITLE
Исходные данные

### ISSUE THREAD

**Issue by kwetril** [sandello/bigdatashad-2015#2]
Здравствуйте,
В описании ДЗ сказано, что логи будут лежать в таком фомате:
access.log.2015-09-26  <-- Текущий записываемый лог
access.log.2015-09-25  <-- Лог за 25 сентября 2015 года
access.log.2015-09-24  <-- Лог за 24 сентября 2015 года
access.log.2015-09-23  <-- Лог за 23 сентября 2015 года
Но последние дни все пишется в один файл: /home/sandello/logs/access.log. Надо ли разделять его самостоятельно или просто пусконаладочные работы еще не завершены?

**Comment by sandello** [comment]
Привет!

Да, пусконаладочные работы чуть затянулись; в данный момент логи порождаются корректно и с разбивкой по файлам.

**Comment by sandello** [comment]
Пусть issue побудет некоторое время открытым; вероятно, у коллег будет аналогичный вопрос.
