### ISSUE TITLE
Диапазон дат в системе самопроверки

### ISSUE THREAD

**Issue by kwetril** [sandello/bigdatashad-2015#3]
Здравствуйте,
Кажется, что значения из полей для дат не используются системой самопроверки при отправке запроса. Приложение пишет в лог всегда такой запрос:
/api/hw1?start_date=2015-09-20&end_date=2015-10-01
При этом сама система самопроверки падает с 500-ой ошибкой. Возможно это связано с тем, что для дат, метрики для которых не расчитаны, я возвращаю пустой объект: {}.
Проверьте, пожалуйста.

**Comment by sandello** [comment]
Привет.

Поправил, попробуй еще раз, пожалуйста. Также добавил трекинг исключений, чтобы быстрее реагировать на такие кейсы.

**Comment by kwetril** [comment]
Спасибо, вроде работает.
Запрашивает только заданный период, ошибки о неверном формате полей выводит, графики рисует, смотрится неплохо)
