### ISSUE TITLE
Нет доступа к hdfs.

### ISSUE THREAD

**Issue by shvetsovroman** [sandello/bigdatashad-2015#4]
Добрый день! 
Сегодня с такой ситуацией при попытке работы с hdfs:
shvetsov@hadoop2-00:~$ cd /hdfs
-bash: cd: /hdfs: Transport endpoint is not connected
Подскажите, пожалуйста, это проблемы с hdfs?

**Comment by ShAlex** [comment]
Да, это проблемы с hdfs. Уже в курсе этой проблемы. Используйте $hdfs dfs -help

**Comment by sandello** [comment]
Все известные проблемы были устранены.
